import fs from 'fs';

export interface PhotoStory {
  id: string;
  index: number;
  src: string;
  image: string;
  date?: string;
  title: string;
  marathiTitle?: string;
  category: 'Healthcare & Impact' | 'Civil Engineering' | 'Rotary Leadership' | 'Youth & Mentorship' | 'Culture & Heritage' | 'Life & Fellowship';
  caption: string;
  location: string;
  year?: string;
  orientation: 'portrait' | 'landscape' | 'square';
  featured: boolean;
  tags: string[];
}

export const allPhotoStories: PhotoStory[] = [
  {
    id: "p01",
    index: 1,
    src: "/photos/mahesh-photo-01.jpg",
    image: "/photos/mahesh-photo-01.jpg",
    title: "Rotary Utsav 2024 Celebration",
    marathiTitle: "रोटरी उत्सव २०२४ सोहळा",
    category: "Rotary Leadership",
    caption: "Rtn. Mahesh Mokalkar on stage at Rotary Utsav 2024, celebrating community service, cultural unity, and three decades of leadership across District 3030.",
    location: "Wardha, Maharashtra",
    date: "2024",
    orientation: "portrait",
    featured: true,
    tags: ["Rotary Utsav", "Leadership", "Fellowship", "Keynote"]
  },
  {
    id: "p02",
    index: 2,
    src: "/photos/mahesh-photo-02.jpg",
    image: "/photos/mahesh-photo-02.jpg",
    title: "The Warmth of Servant Leadership",
    marathiTitle: "स्नेहशील आणि समर्पित नेतृत्व",
    category: "Life & Fellowship",
    caption: "A warm and approachable close-up portrait of Mahesh Mokalkar, wearing a designer textured blazer adorned with his Rotary pin.",
    location: "Maharashtra",
    date: "2024",
    orientation: "portrait",
    featured: false,
    tags: ["Portrait", "Rotary Pin", "Fellowship"]
  },
  {
    id: "p03",
    index: 3,
    src: "/photos/mahesh-photo-03.jpg",
    image: "/photos/mahesh-photo-03.jpg",
    title: "The Voice of Purpose",
    marathiTitle: "विचारांचे प्रभावी प्रकटीकरण",
    category: "Rotary Leadership",
    caption: "Addressing a leadership assembly with eloquence and clarity in a blue Nehru jacket with Rotary insignia.",
    location: "District 3030 Assembly",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Keynote", "Public Speaking", "Rotary Leadership"]
  },
  {
    id: "p04",
    index: 4,
    src: "/photos/mahesh-photo-04.jpg",
    image: "/photos/mahesh-photo-04.jpg",
    title: "Simplicity & Indian Values",
    marathiTitle: "साधेपणा आणि भारतीय संस्कार",
    category: "Culture & Heritage",
    caption: "Full-length portrait in immaculate white kurta pyjama and beige khadi vest in a garden courtyard, embodying Gandhian simplicity.",
    location: "Wardha",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Khadi", "Traditional Attire", "Wardha Culture"]
  },
  {
    id: "p05",
    index: 5,
    src: "/photos/mahesh-photo-05.jpg",
    image: "/photos/mahesh-photo-05.jpg",
    title: "Serenity in Tradition",
    marathiTitle: "परंपरेत रमलेले व्यक्तिमत्त्व",
    category: "Culture & Heritage",
    caption: "Standing dignified in traditional handloom vest, reflecting peace of mind, cultural groundedness, and approachable humility.",
    location: "Wardha, Maharashtra",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Culture", "Tradition", "Elegance"]
  },
  {
    id: "p06",
    index: 6,
    src: "/photos/mahesh-photo-06.jpg",
    image: "/photos/mahesh-photo-06.jpg",
    title: "Official District Governor Portrait (RID 3030)",
    marathiTitle: "जिल्हा प्रांतपाल अधिकृत छायाचित्र (RID ३०३०)",
    category: "Rotary Leadership",
    caption: "The official District Governor portrait of Rtn. PDG Mahesh Mokalkar in tailored suit, international flag tie, and official metallic DG collar badge (2016-17).",
    location: "Rotary International District 3030",
    date: "2016 - 2017",
    orientation: "portrait",
    featured: true,
    tags: ["District Governor", "Official Portrait", "RID 3030", "Rotary International"]
  },
  {
    id: "p07",
    index: 7,
    src: "/photos/mahesh-photo-07.jpg",
    image: "/photos/mahesh-photo-07.jpg",
    title: "Chilled RO Clean Drinking Water Station",
    marathiTitle: "स्वच्छ आरओ पेयजल प्रकल्प लोकार्पण - अमरावती रेल्वे स्टेशन",
    category: "Healthcare & Impact",
    caption: "Dedicating a high-capacity Chilled RO Clean Drinking Water Plant for thousands of daily railway commuters at Amravati Railway Station under Rotary District 3030.",
    location: "Amravati Railway Station",
    date: "2017",
    orientation: "landscape",
    featured: true,
    tags: ["Clean Water", "RO Plant", "Indian Railways", "Public Welfare"]
  },
  {
    id: "p08",
    index: 8,
    src: "/photos/mahesh-photo-08.jpg",
    image: "/photos/mahesh-photo-08.jpg",
    title: "Tranquility in Nature",
    marathiTitle: "निसर्गाच्या सान्निध्यात शांत क्षण",
    category: "Life & Fellowship",
    caption: "Relaxing outdoors in a flower garden on a carved stone ledge, smiling peacefully away from the bustling demands of public administration.",
    location: "Kashmir Garden",
    date: "2022",
    orientation: "square",
    featured: false,
    tags: ["Nature", "Peace", "Lifestyle"]
  },
  {
    id: "p09",
    index: 9,
    src: "/photos/mahesh-photo-09.jpg",
    image: "/photos/mahesh-photo-09.jpg",
    title: "Master Trainer & Keynote Orator",
    marathiTitle: "मार्गदर्शक आणि प्रभावी वक्ता",
    category: "Rotary Leadership",
    caption: "Conducting an interactive training masterclass with a wireless headset microphone, sharing insights on organizational growth and service ethics.",
    location: "Leadership Academy RID 3030",
    date: "2022",
    orientation: "landscape",
    featured: false,
    tags: ["Trainer", "Keynote", "Public Speaking"]
  },
  {
    id: "p10",
    index: 10,
    src: "/photos/mahesh-photo-10.jpg",
    image: "/photos/mahesh-photo-10.jpg",
    title: "Vitality & Joie de Vivre",
    marathiTitle: "उत्साह, तंदुरुस्ती आणि जीवननिष्ठा",
    category: "Life & Fellowship",
    caption: "Enjoying a refreshing swim, capturing Mahesh's youthful energy, physical vitality, and boundless positivity towards every moment in life.",
    location: "Resort Retreat",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Fitness", "Vitality", "Life Energy"]
  },
  {
    id: "p11",
    index: 11,
    src: "/photos/mahesh-photo-11.jpg",
    image: "/photos/mahesh-photo-11.jpg",
    title: "A Heartfelt Smile",
    marathiTitle: "हृदयस्पर्शी हास्य",
    category: "Life & Fellowship",
    caption: "Close-up portrait capturing the genuine warmth and compassion that defines Mahesh's relationships with colleagues, citizens, and friends.",
    location: "Nagpur, Maharashtra",
    date: "2024",
    orientation: "portrait",
    featured: false,
    tags: ["Portrait", "Warmth", "Smile"]
  },
  {
    id: "p12",
    index: 12,
    src: "/photos/mahesh-photo-12.jpg",
    image: "/photos/mahesh-photo-12.jpg",
    title: "Maharashtrian Royal Pheta & Festive Attire",
    marathiTitle: "पारंपरिक महाराष्ट्रीयन फेटा आणि गौरव",
    category: "Culture & Heritage",
    caption: "Dressed in an intricately tied Maharashtrian festive Pheta (turban) and brocade jacket, celebrating Vidarbha's rich cultural heritage.",
    location: "Wardha",
    date: "2023",
    orientation: "portrait",
    featured: true,
    tags: ["Pheta", "Marathi Culture", "Heritage", "Festivity"]
  },
  {
    id: "p13",
    index: 13,
    src: "/photos/mahesh-photo-13.jpg",
    image: "/photos/mahesh-photo-13.jpg",
    title: "Quiet Focus",
    marathiTitle: "चिंतनशील मुद्रा",
    category: "Life & Fellowship",
    caption: "A quiet moment of reflection on upcoming public infrastructure and community welfare blueprints.",
    location: "Wardha",
    date: "2021",
    orientation: "portrait",
    featured: false,
    tags: ["Focus", "Thought Leader"]
  },
  {
    id: "p14",
    index: 14,
    src: "/photos/mahesh-photo-14.jpg",
    image: "/photos/mahesh-photo-14.jpg",
    title: "Carnival Lights at Rotary Utsav",
    marathiTitle: "रोटरी उत्सवातील चैतन्यमय संध्याकाळ",
    category: "Life & Fellowship",
    caption: "Mahesh Mokalkar in an artistic jacket before an illuminated Ferris wheel at night during the grand community Rotary Utsav.",
    location: "Wardha Fair Grounds",
    date: "2024",
    orientation: "portrait",
    featured: true,
    tags: ["Rotary Utsav", "Festival", "Night Lights", "Joy"]
  },
  {
    id: "p15",
    index: 15,
    src: "/photos/mahesh-photo-15.jpg",
    image: "/photos/mahesh-photo-15.jpg",
    title: "Architectural Symmetry & Poise",
    marathiTitle: "भव्य परिसरातील शांत व्यक्तिमत्त्व",
    category: "Life & Fellowship",
    caption: "Standing in crisp black formal attire by a tranquil resort pool and colonial-style villas.",
    location: "Goa Conference Retreat",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Executive", "Elegance", "Poise"]
  },
  {
    id: "p16",
    index: 16,
    src: "/photos/mahesh-photo-16.jpg",
    image: "/photos/mahesh-photo-16.jpg",
    title: "Evening Fellowship Hour",
    marathiTitle: "रोटरी स्नेहसंमेलन संध्याकाळ",
    category: "Life & Fellowship",
    caption: "Evening gathering in a double-breasted grey pinstripe vest, meeting fellow Rotarians and civic delegates.",
    location: "Rotary Fellowship Evening",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Fellowship", "Style", "Evening"]
  },
  {
    id: "p17",
    index: 17,
    src: "/photos/mahesh-photo-17.jpg",
    image: "/photos/mahesh-photo-17.jpg",
    title: "Artistic Expression & Rotary Peace",
    marathiTitle: "कलात्मक दृष्टी आणि रोटरी शांतीचा संदेश",
    category: "Rotary Leadership",
    caption: "Wearing a bespoke designer jacket featuring brush-stroke textures and the official Rotary Peace Dove lapel pin.",
    location: "Rotary Peace Conclave",
    date: "2024",
    orientation: "portrait",
    featured: true,
    tags: ["Rotary Peace", "Designer Jacket", "Peace Dove", "Artistic"]
  },
  {
    id: "p18",
    index: 18,
    src: "/photos/mahesh-photo-18.jpg",
    image: "/photos/mahesh-photo-18.jpg",
    title: "A Child at Heart: Celebrating Life",
    marathiTitle: "आनंदी मन आणि निखळ हास्य",
    category: "Life & Fellowship",
    caption: "Playfully striking a pose beside whimsical clown sculptures, reminding us that genuine humility includes the ability to smile freely.",
    location: "Civic Cultural Center",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Joy", "Humor", "Playful"]
  },
  {
    id: "p19",
    index: 19,
    src: "/photos/mahesh-photo-19.jpg",
    image: "/photos/mahesh-photo-19.jpg",
    title: "Spreading Smiles Across Generations",
    marathiTitle: "सगळ्यांसोबत हसणारा आणि आनंद वाटणारा नेता",
    category: "Life & Fellowship",
    caption: "Playfully mimicking colorful statues with open arms and full laughter — showing the cheerful spirit he brings to all community service.",
    location: "Cultural Pavilion",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Laughter", "Joy", "Community Spirit"]
  },
  {
    id: "p20",
    index: 20,
    src: "/photos/mahesh-photo-20.jpg",
    image: "/photos/mahesh-photo-20.jpg",
    title: "Padmasana: Inner Equilibrium & Mindfulness",
    marathiTitle: "पद्मासन: आत्मिक शांती आणि ध्यान साधना",
    category: "Culture & Heritage",
    caption: "Seated in deep Padmasana yogic meditation before a luminous golden wall, demonstrating the daily mindfulness and inner calm that fuels his tireless public work.",
    location: "Meditation Hall",
    date: "2023",
    orientation: "square",
    featured: true,
    tags: ["Meditation", "Padmasana", "Yoga", "Mindfulness", "Philosophy"]
  },
  {
    id: "p21",
    index: 21,
    src: "/photos/mahesh-photo-21.jpg",
    image: "/photos/mahesh-photo-21.jpg",
    title: "The Joy of Being Approachable",
    marathiTitle: "सुलभ, सहज आणि आपुलकीचे नाते",
    category: "Life & Fellowship",
    caption: "A wider portrait highlighting how Mahesh breaks formal barriers to connect with people of all ages through humor and genuine warmth.",
    location: "Cultural Plaza",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Warmth", "Connection"]
  },
  {
    id: "p22",
    index: 22,
    src: "/photos/mahesh-photo-22.jpg",
    image: "/photos/mahesh-photo-22.jpg",
    title: "The Distinguished Statesman",
    marathiTitle: "प्रतिष्ठित प्रशासक आणि मार्गदर्शक",
    category: "Civil Engineering",
    caption: "Distinguished portrait of Mahesh Mokalkar in executive black Jodhpuri bandhgala with national tricolor emblem pin, against verdant greenery.",
    location: "Government Complex, Wardha",
    date: "2024",
    orientation: "portrait",
    featured: true,
    tags: ["Executive", "Bandhgala", "Statesman", "Tricolor Pin"]
  },
  {
    id: "p23",
    index: 23,
    src: "/photos/mahesh-photo-23.jpg",
    image: "/photos/mahesh-photo-23.jpg",
    title: "AGLS Rajdharma Leadership Keynote",
    marathiTitle: "राजधर्म - असिस्टंट गव्हर्नर प्रशिक्षण कार्यशाळा",
    category: "Rotary Leadership",
    caption: "Delivering the keynote address at 'राजधर्म' Assistant Governor Learning Seminar (AGLS), mentoring incoming district leaders on transparent and visionary governance.",
    location: "Rotary Leadership Academy",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["AGLS", "Rajdharma", "District Trainer", "Mentorship"]
  },
  {
    id: "p24",
    index: 24,
    src: "/photos/mahesh-photo-24.jpg",
    image: "/photos/mahesh-photo-24.jpg",
    title: "Strategic Vision: DISHA Conclave",
    marathiTitle: "दिशा नेतृत्व परिषद - सखोल विचारमंथन",
    category: "Rotary Leadership",
    caption: "Deep in contemplation during the DISHA leadership conclave in Nagpur, wearing the official red Rotary polo embroidered with Rotary wheel.",
    location: "Nagpur, Maharashtra",
    date: "2023",
    orientation: "portrait",
    featured: true,
    tags: ["DISHA", "Leadership Summit", "Vision", "Rotary Polo"]
  },
  {
    id: "p25",
    index: 25,
    src: "/photos/mahesh-photo-25.jpg",
    image: "/photos/mahesh-photo-25.jpg",
    title: "Nagpuri Star Award & Public Recognition",
    marathiTitle: "नागपुरी स्टार पुरस्कार आणि सन्मान",
    category: "Rotary Leadership",
    caption: "Addressing a packed auditorium with The Hitavada headlines on display, speaking on the power of grassroots social service.",
    location: "Nagpur Auditorium",
    date: "2022",
    orientation: "landscape",
    featured: true,
    tags: ["Hitavada", "Award Conclave", "Public Address"]
  },
  {
    id: "p26",
    index: 26,
    src: "/photos/mahesh-photo-26.jpg",
    image: "/photos/mahesh-photo-26.jpg",
    title: "Architectural Wonder: Khajuraho Temple Steps",
    marathiTitle: "खजुराहो मंदिराच्या पायऱ्यांवर - ऐतिहासिक वास्तुशिल्प",
    category: "Culture & Heritage",
    caption: "Sitting on the ancient sandstone steps of Khajuraho temples in purple Rotary 3030 polo, admiring centuries of structural engineering mastery.",
    location: "Khajuraho, Madhya Pradesh",
    date: "2022",
    orientation: "portrait",
    featured: true,
    tags: ["Khajuraho", "Heritage", "Ancient Engineering", "Travel"]
  },
  {
    id: "p27",
    index: 27,
    src: "/photos/mahesh-photo-27.jpg",
    image: "/photos/mahesh-photo-27.jpg",
    title: "Holding Up the Earth: Geotechnical Humor",
    marathiTitle: "प्रचंड शिळेचा तोल सावरताना - मिश्किल क्षण",
    category: "Civil Engineering",
    caption: "Playfully pretending to hold up a massive balancing rock overhang like Atlas, uniting structural engineering curiosity with lighthearted wit.",
    location: "Natural Rock Formations",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Rock Mechanics", "Engineering Wit", "Humor"]
  },
  {
    id: "p28",
    index: 28,
    src: "/photos/mahesh-photo-28.jpg",
    image: "/photos/mahesh-photo-28.jpg",
    title: "Testing the Overhang",
    marathiTitle: "निसर्गाची रचना आणि अभियांत्रिक कुतूहल",
    category: "Civil Engineering",
    caption: "Examining the natural equilibrium of granite balancing boulders during a geological field study.",
    location: "Deccan Plateau Outcrops",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Geology", "Balancing Rock"]
  },
  {
    id: "p29",
    index: 29,
    src: "/photos/mahesh-photo-29.jpg",
    image: "/photos/mahesh-photo-29.jpg",
    title: "Sunset at Konark Sun Temple",
    marathiTitle: "कोनार्क सूर्य मंदिराच्या प्रांगणात",
    category: "Culture & Heritage",
    caption: "Standing in awe before the 13th-century Konark Sun Temple at dusk, studying the stone chariot architecture and timeless engineering genius.",
    location: "Konark, Odisha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Konark", "Sun Temple", "UNESCO Heritage", "Civil Engineering Heritage"]
  },
  {
    id: "p30",
    index: 30,
    src: "/photos/mahesh-photo-30.jpg",
    image: "/photos/mahesh-photo-30.jpg",
    title: "The Executive Desk: PWD Sub-Division No. 2, Wardha",
    marathiTitle: "सार्वजनिक बांधकाम उपविभाग क्र. २, वर्धा - अधिकृत कार्यालय",
    category: "Civil Engineering",
    caption: "Mahesh Mokalkar at his official PWD Sub-Divisional Engineer executive desk in Wardha, reviewing civil blueprints alongside the Ashoka Stambh emblem.",
    location: "PWD Office, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["PWD Wardha", "Blueprints", "Executive Office", "Ashoka Stambh", "Sub-Divisional Engineer"]
  },
  {
    id: "p31",
    index: 31,
    src: "/photos/mahesh-photo-31.jpg",
    image: "/photos/mahesh-photo-31.jpg",
    title: "Executive Confidence in Camel Blazer",
    marathiTitle: "आत्मविश्वासाने परिपूर्ण नेतृत्व",
    category: "Life & Fellowship",
    caption: "Full-length portrait in tailored camel gold blazer, dark shirt, and brown dress shoes with official Rotary pin.",
    location: "Mumbai Conference",
    date: "2024",
    orientation: "portrait",
    featured: false,
    tags: ["Executive", "Fashion", "Conference"]
  },
  {
    id: "p32",
    index: 32,
    src: "/photos/mahesh-photo-32.jpg",
    image: "/photos/mahesh-photo-32.jpg",
    title: "Administrative Presence: Collectorate Steps",
    marathiTitle: "जिल्हाधिकारी कार्यालय प्रांगण - प्रशासकीय प्रतिष्ठा",
    category: "Civil Engineering",
    caption: "Flanked by police escort on the grand entrance stairs of the Collectorate / Government Administrative Complex in brown Jodhpuri suit.",
    location: "Collector Office Building, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Collectorate", "Government Administration", "PWD Landmark", "Wardha"]
  },
  {
    id: "p33",
    index: 33,
    src: "/photos/mahesh-photo-33.jpg",
    image: "/photos/mahesh-photo-33.jpg",
    title: "Energy on the Turf: Sports Fellowship",
    marathiTitle: "खेळाच्या मैदानावर - मैत्री आणि चैतन्य",
    category: "Life & Fellowship",
    caption: "Thumbs-up on the cricket turf in athletic sports attire, demonstrating that vibrant sportsmanship and camaraderie go hand in hand with service.",
    location: "Rotary Sports Turf, Wardha",
    date: "2024",
    orientation: "portrait",
    featured: true,
    tags: ["Sports", "Cricket", "Turf", "Fellowship", "Energy"]
  },
  {
    id: "p34",
    index: 34,
    src: "/photos/mahesh-photo-34.jpg",
    image: "/photos/mahesh-photo-34.jpg",
    title: "Dignified Earthiness in Khadi",
    marathiTitle: "खादीच्या पोषाखातील साधे आणि प्रसन्न रूप",
    category: "Culture & Heritage",
    caption: "Dignified portrait in textured earthy khadi bandhgala with national flag lapel pin, surrounded by traditional festive turbans.",
    location: "Wardha",
    date: "2023",
    orientation: "portrait",
    featured: false,
    tags: ["Khadi", "Bandhgala", "Tricolor Pin"]
  },
  {
    id: "p35",
    index: 35,
    src: "/photos/mahesh-photo-35.jpg",
    image: "/photos/mahesh-photo-35.jpg",
    title: "Elegance Amidst Architectural Art",
    marathiTitle: "कलात्मक पार्श्वभूमीतील देखणे व्यक्तिमत्त्व",
    category: "Life & Fellowship",
    caption: "Standing in an olive blazer against a dramatic black geometric relief wall crowned with orchids and gold palms.",
    location: "Gala Conclave, Mumbai",
    date: "2024",
    orientation: "portrait",
    featured: false,
    tags: ["Gala", "Luxury", "Elegance"]
  },
  {
    id: "p36",
    index: 36,
    src: "/photos/mahesh-photo-36.jpg",
    image: "/photos/mahesh-photo-36.jpg",
    title: "Restoring Mobility: Jaipur Foot & Prosthetic Limb Camp",
    marathiTitle: "कृत्रिम अवयव (जयपूर फूट) वाटप शिबिर - नवी उमेद",
    category: "Healthcare & Impact",
    caption: "Beneficiaries of the artificial prosthetic limbs drive proudly showing their new legs and mobility aids alongside Mahesh Mokalkar and team — restoring dignity and livelihood.",
    location: "Amravati / Wardha",
    date: "2018",
    orientation: "landscape",
    featured: true,
    tags: ["Jaipur Foot", "Prosthetic Limbs", "Disability Empowerment", "Sapne Sach Hue", "Humanitarian"]
  },
  {
    id: "p37",
    index: 37,
    src: "/photos/mahesh-photo-37.jpg",
    image: "/photos/mahesh-photo-37.jpg",
    title: "Grassroots Connection at Mahesh Seva Samiti Camp",
    marathiTitle: "श्री महेश सेवा समिती शिबिरातील आपुलकीचे क्षण",
    category: "Healthcare & Impact",
    caption: "Standing shoulder to shoulder with a rural elder beneficiary and young volunteer under the banner of Shri Mahesh Seva Samiti.",
    location: "Amravati",
    date: "2018",
    orientation: "portrait",
    featured: false,
    tags: ["Seva Samiti", "Grassroots", "Empowerment"]
  },
  {
    id: "p38",
    index: 38,
    src: "/photos/mahesh-photo-38.jpg",
    image: "/photos/mahesh-photo-38.jpg",
    title: "Heart to Heart: Listening to Beneficiaries",
    marathiTitle: "लाभार्थ्यांशी थेट संवाद आणि आस्थेवाईक विचारपूस",
    category: "Healthcare & Impact",
    caption: "Engaging in an earnest one-on-one conversation with a beneficiary fitted with a new prosthetic limb, ensuring comfortable fit and independent mobility.",
    location: "Prosthetic Center",
    date: "2018",
    orientation: "portrait",
    featured: true,
    tags: ["Compassion", "Listening", "Mobility"]
  },
  {
    id: "p39",
    index: 39,
    src: "/photos/mahesh-photo-39.jpg",
    image: "/photos/mahesh-photo-39.jpg",
    title: "Heritage Tour with Rotarian Brothers",
    marathiTitle: "रोटरी बंधूंसमवेत ऐतिहासिक मंदिर भेट",
    category: "Life & Fellowship",
    caption: "Exploring the historic gateway of an ancient temple complex with close Rotarian friends, cherishing shared memories and culture.",
    location: "Vidarbha Heritage Site",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Temple", "Heritage", "Friends"]
  },
  {
    id: "p40",
    index: 40,
    src: "/photos/mahesh-photo-40.jpg",
    image: "/photos/mahesh-photo-40.jpg",
    title: "Grassroots Deliberation & Community Council",
    marathiTitle: "ग्रामीण भागातील विकासकामांची चर्चा",
    category: "Civil Engineering",
    caption: "Conducting an open dialogue with local village elders and civic engineers on public drinking water and road connectivity needs.",
    location: "Rural Wardha",
    date: "2022",
    orientation: "landscape",
    featured: false,
    tags: ["Village Council", "Public Consultation", "Rural Infrastructure"]
  },
  {
    id: "p41",
    index: 41,
    src: "/photos/mahesh-photo-41.jpg",
    image: "/photos/mahesh-photo-41.jpg",
    title: "Sevagram Ashram Pilgrimage: Living the Gandhian Way",
    marathiTitle: "सेवाग्राम आश्रम भेट - गांधीजींच्या विचारांचा वारसा",
    category: "Culture & Heritage",
    caption: "Leading a delegation of Rotarians wearing khadi garlands on a sacred visit to Mahatma Gandhi's Sevagram Ashram in Wardha.",
    location: "Sevagram Ashram, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Sevagram", "Mahatma Gandhi", "Wardha Heritage", "Khadi"]
  },
  {
    id: "p42",
    index: 42,
    src: "/photos/mahesh-photo-42.jpg",
    image: "/photos/mahesh-photo-42.jpg",
    title: "Under the Banyan of Sevagram Ashram",
    marathiTitle: "सेवाग्रामच्या ऐतिहासिक वृक्षाखाली रोटरी सहकाऱ्यांसोबत",
    category: "Culture & Heritage",
    caption: "Group photo of Rotarians united under the historic tree of Sevagram Ashram, renewing their pledge to Service Above Self.",
    location: "Sevagram Ashram, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Sevagram", "Fellowship", "Gandhian Heritage", "Unity"]
  },
  {
    id: "p43",
    index: 43,
    src: "/photos/mahesh-photo-43.jpg",
    image: "/photos/mahesh-photo-43.jpg",
    title: "Friendship Beyond Badges",
    marathiTitle: "मैत्रीचे अतूट बंध",
    category: "Life & Fellowship",
    caption: "Candid group selfie with fellow Rotarians during an educational excursion across historic temple gateways.",
    location: "Heritage Excursion",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Friendship", "Selfie", "Camaraderie"]
  },
  {
    id: "p44",
    index: 44,
    src: "/photos/mahesh-photo-44.jpg",
    image: "/photos/mahesh-photo-44.jpg",
    title: "Gift of Life: 300+ Pediatric Heart Surgeries",
    marathiTitle: "३०० हून अधिक बालकांच्या हृदय शस्त्रक्रियांना जीवनदान",
    category: "Healthcare & Impact",
    caption: "A deeply moving moment: Mahesh Mokalkar with a young boy who received successful open-heart surgery, alongside his grateful grandfather and Rotarians.",
    location: "District Medical Office",
    date: "2022",
    orientation: "landscape",
    featured: true,
    tags: ["Heart Surgery", "Child Healthcare", "Pediatric Cardiac", "Gift of Life", "Flagship Impact"]
  },
  {
    id: "p45",
    index: 45,
    src: "/photos/mahesh-photo-45.jpg",
    image: "/photos/mahesh-photo-45.jpg",
    title: "Rotary Club Installation & Fellowship Ceremony",
    marathiTitle: "रोटरी क्लब पदग्रहण सोहळा आणि संघटन",
    category: "Rotary Leadership",
    caption: "District leaders and club presidents gathered in formal maroon blazers and presidential collar for an annual charter handover.",
    location: "Rotary Hall, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Installation", "Club President", "Fellowship"]
  },
  {
    id: "p46",
    index: 46,
    src: "/photos/mahesh-photo-46.jpg",
    image: "/photos/mahesh-photo-46.jpg",
    title: "A Young Heart Beats Strong",
    marathiTitle: "पुन्हा हसणारे बालपण - हृदय शस्त्रक्रिया लाभार्थी",
    category: "Healthcare & Impact",
    caption: "Close-up with the young cardiac surgery beneficiary and his grandfather, showing the tender, life-saving impact of Rotary medical grants.",
    location: "Wardha",
    date: "2022",
    orientation: "portrait",
    featured: true,
    tags: ["Pediatric Cardiac", "Child Surgery", "Life Saved", "Compassion"]
  },
  {
    id: "p47",
    index: 47,
    src: "/photos/mahesh-photo-47.jpg",
    image: "/photos/mahesh-photo-47.jpg",
    title: "Life Partners in Service: Aarti & Mahesh Mokalkar",
    marathiTitle: "समाजसेवेतील सहप्रवासी - आरती व महेश मोकलकर",
    category: "Life & Fellowship",
    caption: "Mahesh Mokalkar dancing joyfully with arms outstretched alongside his wife R/Ann Aarti Mokalkar in front of a tribal folk dance mural. Both are Major Donors Level Four.",
    location: "Cultural Auditorium",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Aarti Mokalkar", "Family", "Major Donors Level 4", "Joy", "Partnership"]
  },
  {
    id: "p48",
    index: 48,
    src: "/photos/mahesh-photo-48.jpg",
    image: "/photos/mahesh-photo-48.jpg",
    title: "Together in Love, Devotion & Service",
    marathiTitle: "सहजीवनाचा सुंदर प्रवास - आरती व महेश",
    category: "Life & Fellowship",
    caption: "A warm, natural selfie of Mahesh Mokalkar and wife Aarti Mokalkar with lush hill greenery and traditional cottages behind them.",
    location: "Nature Retreat",
    date: "2023",
    orientation: "portrait",
    featured: true,
    tags: ["Aarti Mokalkar", "Selfie", "Family Man", "Companion"]
  },
  {
    id: "p49",
    index: 49,
    src: "/photos/mahesh-photo-49.jpg",
    image: "/photos/mahesh-photo-49.jpg",
    title: "PWD Public Infrastructure Inspection Delegation",
    marathiTitle: "सार्वजनिक रुग्णालय व प्रशासकीय इमारत पाहणी दौरा",
    category: "Civil Engineering",
    caption: "Leading a senior government delegation and engineering review inside a newly constructed public hospital and civil complex in Maharashtra.",
    location: "Civil Hospital Complex",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["PWD Inspection", "Civil Hospital", "Infrastructure", "Engineering Delegation"]
  },
  {
    id: "p50",
    index: 50,
    src: "/photos/mahesh-photo-50.jpg",
    image: "/photos/mahesh-photo-50.jpg",
    title: "Indian Oil CSR Portable X-Ray Donation Handover",
    marathiTitle: "इंडियन ऑइल सीएसआर पोर्टेबल एक्स-रे यंत्र हस्तांतरण सोहळा",
    category: "Healthcare & Impact",
    caption: "Chief Guest PDG Mahesh Mokalkar handing over a battery-operated portable X-Ray machine to Washim District & Rural Hospital, funded through Indian Oil CSR and Rotary.",
    location: "District Hospital, Washim",
    date: "2024",
    orientation: "landscape",
    featured: true,
    tags: ["Indian Oil CSR", "Portable X-Ray", "Washim District Hospital", "Chief Guest", "Healthcare"]
  },
  {
    id: "p51",
    index: 51,
    src: "/photos/mahesh-photo-51.jpg",
    image: "/photos/mahesh-photo-51.jpg",
    title: "Civil Project Handover & Felicitation",
    marathiTitle: "प्रकल्प पूर्णत्वाचा गौरव - अभियंता चमू",
    category: "Civil Engineering",
    caption: "Receiving congratulatory honors alongside site engineers and public officials upon the successful completion of a landmark government facility.",
    location: "Administrative Building Site",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Felicitation", "Project Handover", "Engineers"]
  },
  {
    id: "p52",
    index: 52,
    src: "/photos/mahesh-photo-52.jpg",
    image: "/photos/mahesh-photo-52.jpg",
    title: "Healthcare Partnership with District Civil Surgeon",
    marathiTitle: "जिल्हा शल्य चिकित्सक, वाशिम यांच्या समवेत सन्मान",
    category: "Healthcare & Impact",
    caption: "Felicitation ceremony in the chamber of the Chief Civil Surgeon, District Hospital Washim, acknowledging the arrival of critical diagnostic medical machinery.",
    location: "Washim District Hospital",
    date: "2024",
    orientation: "landscape",
    featured: false,
    tags: ["Civil Surgeon", "Washim", "Hospital Partnership"]
  },
  {
    id: "p53",
    index: 53,
    src: "/photos/mahesh-photo-53.jpg",
    image: "/photos/mahesh-photo-53.jpg",
    title: "District Healthcare Review & Hospital Support",
    marathiTitle: "जिल्हा रुग्णालय वैद्यकीय सुविधा आढावा बैठक",
    category: "Healthcare & Impact",
    caption: "Rotary and government leaders assembled with medical superintendents to plan upcoming maternal diagnostic camps and pediatric cardiac screenings.",
    location: "District Hospital, Washim",
    date: "2024",
    orientation: "landscape",
    featured: false,
    tags: ["Medical Superintendents", "Diagnostic Camps", "Washim"]
  },
  {
    id: "p54",
    index: 54,
    src: "/photos/mahesh-photo-54.jpg",
    image: "/photos/mahesh-photo-54.jpg",
    title: "Strategic Dialogue with Chief Civil Surgeon",
    marathiTitle: "ग्रामीण आरोग्यासाठी उच्चस्तरीय चर्चा",
    category: "Healthcare & Impact",
    caption: "Seated beside the Chief Civil Surgeon of Washim District Hospital, deliberating on mobilizing CSR resources to strengthen rural healthcare access.",
    location: "Washim District Hospital",
    date: "2024",
    orientation: "landscape",
    featured: true,
    tags: ["Civil Surgeon", "CSR Collaboration", "Rural Healthcare"]
  },
  {
    id: "p55",
    index: 55,
    src: "/photos/mahesh-photo-55.jpg",
    image: "/photos/mahesh-photo-55.jpg",
    title: "Youth Leadership Surge: Rotaract Rejoice Conference",
    marathiTitle: "युवा नेतृत्वाचा महाकुंभ - रोटरॅक्ट रिजॉईस परिषद",
    category: "Youth & Mentorship",
    caption: "Surrounded by 25+ dynamic young Rotaractors celebrating youth leadership, innovation, and social drive at the district Rotaract conference (charted 9 Rotaract & 80 Interact clubs).",
    location: "Rotaract District Conference",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Rotaract", "Youth Empowerment", "Rejoice Conference", "Interact", "NextGen"]
  },
  {
    id: "p56",
    index: 56,
    src: "/photos/mahesh-photo-56.jpg",
    image: "/photos/mahesh-photo-56.jpg",
    title: "Mentorship & Hearty Laughter with Young Leaders",
    marathiTitle: "युवा मित्रांसोबत हास्यकल्लोळ आणि आपुलकीचे मार्गदर्शन",
    category: "Youth & Mentorship",
    caption: "Relaxed armchair session with young Rotaract leaders gathered closely around Mahesh, erupting in spontaneous laughter and heartfelt mentorship.",
    location: "Youth Leadership Retreat",
    date: "2023",
    orientation: "portrait",
    featured: true,
    tags: ["Mentorship", "Youth", "Laughter", "Rotaract Leaders"]
  },
  {
    id: "p57",
    index: 57,
    src: "/photos/mahesh-photo-57.jpg",
    image: "/photos/mahesh-photo-57.jpg",
    title: "Inauguration of Advanced Ultrasound Sonography Machine",
    marathiTitle: "अद्ययावत सोनोग्राफी यंत्र लोकार्पण - शालिनीताई मेघे रुग्णालय",
    category: "Healthcare & Impact",
    caption: "Dedicating an Advanced Ultrasound Sonography machine gifted by The Rotary Foundation RID 3030 to Shalinitai Meghe Mother & Child Hospital for maternal diagnostic care.",
    location: "Shalinitai Meghe Mother & Child Hospital",
    date: "2024",
    orientation: "square",
    featured: true,
    tags: ["TRF Grant", "Sonography Machine", "Maternal Care", "Shalinitai Meghe Hospital", "Inauguration"]
  },
  {
    id: "p58",
    index: 58,
    src: "/photos/mahesh-photo-58.jpg",
    image: "/photos/mahesh-photo-58.jpg",
    title: "Grassroots Consultation in Wardha",
    marathiTitle: "स्थानिक कार्यकर्त्यांशी थेट संवाद",
    category: "Civil Engineering",
    caption: "Listening to community elders and engineers regarding civic water infrastructure and school facility development.",
    location: "Wardha",
    date: "2023",
    orientation: "landscape",
    featured: false,
    tags: ["Consultation", "Grassroots"]
  },
  {
    id: "p59",
    index: 59,
    src: "/photos/mahesh-photo-59.jpg",
    image: "/photos/mahesh-photo-59.jpg",
    title: "Inspiring Local Change in the Community Hall",
    marathiTitle: "सामुदायिक विकासासाठी ग्रामस्थांना मार्गदर्शन",
    category: "Civil Engineering",
    caption: "Mahesh standing before community members under the portrait of Sant Gadge Baba, urging collective responsibility for sanitation and civic cleanliness.",
    location: "Community Center, Wardha",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Sant Gadge Baba", "Cleanliness", "Community Leadership", "Wardha"]
  },
  {
    id: "p60",
    index: 60,
    src: "/photos/mahesh-photo-60.jpg",
    image: "/photos/mahesh-photo-60.jpg",
    title: "Celebrating Milestones with Rotarian Family",
    marathiTitle: "रोटरी कुटुंबासमवेत आनंदोत्सव आणि वाढदिवस",
    category: "Life & Fellowship",
    caption: "A joyful birthday cake cutting celebration with close Rotarian friends, spouses, and team members — celebrating bonds that last a lifetime.",
    location: "Rotary Fellowship Hall",
    date: "2023",
    orientation: "landscape",
    featured: true,
    tags: ["Birthday", "Cake", "Rotary Family", "Fellowship"]
  }
];
